# Default values for cosmocloud-deploy.
# Configuration for Backend, Frontend, and Redis

replicaCount: 1

# Image configurations
image:
  backend:
    repository: shreybatra/sample-backend
    tag: latest
  frontend:
    repository: shreybatra/sample-frontend
    tag: latest
  redis:
    repository: redis
    tag: latest

# Frontend configuration
frontend:
  image:
    repository: shreybatra/sample-frontend
    tag: latest
  port: 5173
  env:
    BACKEND_URL: "http://backend-svc:8000"

# Backend configuration
backend:
  image:
    repository: shreybatra/sample-backend
    tag: latest
  port: 8000
  env:
    REDIS_URI: "redis://redis-svc:6379"

# Service configurations
service:
  backend:
    type: ClusterIP
    port: 8000        # Ensure valid port value (8000)
  frontend:
    type: NodePort
    port: 5173        # Ensure valid port value (5173)
    nodePort: 31000   # Valid NodePort value
  redis:
    type: ClusterIP
    port: 6379        # Valid port value (6379)

# Redis-specific configurations
redis:
  image:
    repository: redis
    tag: latest
  port: 6379  # Ensure this is valid and properly referenced

# Namespace
namespace: default

# ServiceAccount configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations and security contexts
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: / 
          pathType: ImplementationSpecific
  tls: []

# Resources allocation for deployments
resources: {}

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# NodeSelector, tolerations, and affinity for pod scheduling
nodeSelector: {}
tolerations: []
affinity: {}
