apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmocloud-deploy.fullname" . }}-redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.redis.port }}  
      targetPort: 6379
  selector:
    app: redis
