apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmocloud-deploy.fullname" . }}-backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.backend.port }}  # Ensure this is pulling from .Values correctly
      targetPort: 8000
  selector:
    app: backend
